<?php

use Roma\OwnModule\Model\CarModel;

/** @var \Roma\OwnModule\Model\ResourceModel\CarResource\Collection $carsCollection */
$carsCollection = $block->getCarsCollection();

?>

<h1 class="my-block">My Custom Cars Collection:</h1>
<?php if ($carsCollection): ?>
<h1 class="sql-query">Query was:
    <p style="color:red"><?= $carsCollection->getSelect()->__toString(); ?></p>
</h1>
<?php endif; ?>
<div class="container">
    <?php if ($carsCollection): ?>
        <?php foreach ($carsCollection as $car): ?>
            <?php /** @var CarModel $car */ ?>
            <div class="car-id-<?= $car->getId() ?>">
                <h4 class="entity-id">EntityId: <?= $car->getId() ?></h4>
                <h5 class="user-id">UserId: <?= $car->getUserId() ?></h5>
                <h6 class="description">SomeId: <?= $car->getDescription() ?></h6>
                <h6 class="car-id">CarId: <?= $car->getCarId() ?></h6>
                <h6 class="price">Price: <?= $car->getPrice() ?></h6>
                <p class="link">
                    <a class="go-back" href="<?= $block->getUrl('own_route') ?>">Go Back</a>
                </p>
            </div>
            <hr>
        <?php endforeach; ?>
    <?php endif; ?>
</div>