<?php
/** @var \Magento\Framework\View\Element\Template $block */

use Roma\OwnModule\Model\CarCustomerModel;

/** @var \Roma\OwnModule\Block\CarCustomers $block */
$blockName = $block->getNameInLayout();

/** @var \Roma\OwnModule\Model\ResourceModel\CarCustomer\Collection $carCustomersCollection */
$carCustomersCollection = $block->getCarCustomersCollection();
?>

<h1 class="my-block">My Custom Information from theme: my-template.phtml!</h1>
<div class="container">
    <?php foreach ($carCustomersCollection as $carCustomer): ?>
        <?php /** @var CarCustomerModel $carCustomer */ ?>
        <div class="car-customer-id-<?= $carCustomer->getId() ?>">
            <h4 class="entity-id">EntityId: <?= $carCustomer->getId() ?></h4>
            <h3 class="email">Email: <?= $carCustomer->getEmail() ?></h3>
            <h5 class="user-name">UserName: <?= $carCustomer->getName() ?></h5>
            <h6 class="some-id">SomeId: <?= $carCustomer->getSomeId() ?></h6>
            <h6 class="created-at">CreatedAt: <?= $carCustomer->getCreatedAt() ?></h6>
            <p class="link">
                <a class="read-more" href="<?= $block->getUrl('own_route/index/cars', ['user_id' => $carCustomer->getId()]) ?>">See Customer Cars</a>
            </p>
        </div>
    <?php endforeach; ?>
</div>