<?php
use Roma\Stalker\Model\StalkerModel;

/**
 * @var \Roma\Stalker\Block\Stalker $block
 */
$blockName=$block->getInLayout();

$stalkerCollections = $block->getStalkerCollection();
?>
<h1 class="my-block">Stalker shop!</h1>
<div class="custom-app" data-bind="scope:'my-app'">
    <input type="text" id="my-input" name="my_custom" placeholder="Enter List Amount" data-bind="value: myObservableCount">
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "my-app": {
                            "component": "Roma_Stalker/js/filter",
                            "listItemsSelector": ".list-item"
                        }
                    }
                }
            }
        }
    </script>
</div>
<div class="stalker container">
    <?php if (!empty($stalkerCollections)): ?>
    <?php foreach ($stalkerCollections as $stalker): ?>
    <?php /** @var StalkerModel $stalker */ ?>
    <div class="list-item car-customer-id-<?=$stalker->getId() ?>">
        <h4 class="entity-id">EntityId: <?=$stalker->getId() ?></h4>
        <h3 class="nickname">Nickname: <?=$stalker->getNickname() ?></h3>
        <h5 class="grouping">Grouping: <?=$stalker->getGrouping() ?></h5>
        <h6 class="name">Name: <?=$stalker->getName() ?></h6>
        <h4 class="created-at">CreatedAt: <?=$stalker->getCreatedAt() ?></h4>
        <p class="link">
            <?php $href = $block->getStalkerUrl($stalker->getId()); ?>S
            <a class="read-more link-stalker-id-<?= $stalker->getId() ?>" href="<?= $href ?>"><?= __('See Stalker Artifacts of %1', $stalker->getName()) ?></a>
        </p>
    </div>
        <script type="text/x-magento-init">
                {
                    ".link-stalker-id-<?= $stalker->getId() ?>": {
                        "getStalkerArtifacts": {
                            "stalkerId":"<?= $stalker->getId() ?>",
                            "stalkerName":"<?= $stalker->getName() ?>"
                        }
                    }
                }
            </script>
    <?php endforeach; ?>
    <div id="artifacts-container" style="display: none"></div>
    <?php else: ?>
    <div class="message">
        <h1 class="message-error error message"><?= __("There are no stalker found.") ?></h1>
    </div>
    <?php endif; ?>
</div>