<?php
use Roma\Stalker\Model\StalkerModel;

/**
 * @var \Roma\Stalker\Block\Stalker $block
 */
$blockName=$block->getInLayout();

$stalkerCollections = $block->getStalkerCollection();
?>
<h1 class="my-block">Stalker shop!</h1>
<div class="stalker container">
    <?php if (!empty($stalkerCollections)): ?>
    <?php foreach ($stalkerCollections as $stalker): ?>
    <?php /** @var StalkerModel $stalker */ ?>
    <div class="stalker-id-<?=$stalker->getId() ?>">
        <h4 class="entity-id">EntityId: <?=$stalker->getId() ?></h4>
        <h3 class="nickname">Nickname: <?=$stalker->getNickname() ?></h3>
        <h5 class="grouping">Grouping: <?=$stalker->getGrouping() ?></h5>
        <h6 class="name">Name: <?=$stalker->getName() ?></h6>
        <h4 class="created-at">CreatedAt: <?=$stalker->getCreatedAt() ?></h4>
        <p class="link">
            <?php $href = $block->getStalkerUrl($stalker->getId()); ?>
            <a class="read-more" data-mage-init='{
                                            "getStalkerArtifacts": {
                                                "stalkerId":"<?= $stalker->getId() ?>",
                                                "userName":"<?= $stalker->getName() ?>"
                                            }
                                         }'
               href="<?= $href ?>"><?= __('See Customer Cars of %1', $stalker->getName()) ?>
            </a>
        </p>
    </div>
    <?php endforeach; ?>
    <div id="artifacts-container" style="display: none"></div>
    <?php else: ?>
    <div class="message">
        <h1 class="message-error error message"><?= __("There are no stalker found.") ?></h1>
    </div>
    <?php endif; ?>
</div>