<h1>Check license your game!</h1>
<?php
/**
 * @var Roma\Game\Block\CheckGame $block
 */
/** @var \Roma\Game\ViewModel\CheckGame $checkGameLicense */
$checkGameLicense = $block->getData('check_license_game');
$id = $block->getGameId();
$answer='';
if($id!=NULL) {
    try {
        $answer = $checkGameLicense->checkLicenseGame($id);
    } catch (\Magento\Framework\Exception\LocalizedException $e) {

    }
}
?>

<?php if($id!=NULL):?>
<h2>ID = <?= $id ?></h2>
<h1><?= $answer ?></h1>
<?php endif; ?>

<form action="checkGame" method="post">
    <input required="true" name="checkGame" type="text" data-validate="number">
    <input type="submit" value="Check!">
</form>
<h2>You may go back</h2>
<a class="read-more" href="index">Back</a>