<?php

use Roma\Game\Model\GameModel;

/**
 * @var Roma\Game\Block\Games $block
 */
$blockName=$block->getInLayout();
$gameCollection = $block->getGameCollection();
?>

<div class="container">
    <?php if ($gameCollection): ?>
        <?php foreach ($gameCollection as $game): ?>
            <?php /** @var GameModel $game */ ?>
            <div class="game-entity-id-<?= $game->getId() ?>">
                <h2 class="game-id">Game Id: <?= $game->getGameId() ?></h2>
                <h2 class="title">Game Title: <?= $game->getTitle() ?></h2>
                <h3 class="description">Description: <?= $game->getDescription() ?></h3>
                <h2 class="price">Price: <?= $game->getPrice() ?></h2>
                <p class="link">
                    <a class="go-back" href="<?= $block->getUrl('game_route') ?>">Go Back</a>
                </p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>