<?php
use Roma\Game\Model\GameModel;

/**
 * @var Roma\Game\Block\Games $block
 */
$blockName=$block->getInLayout();

$gameCollection = $block->getGameCollection();
?>

<div class="container">
    <?php if ($gameCollection): ?>
        <?php foreach ($gameCollection as $game): ?>
            <?php /** @var GameModel $game */ ?>
            <div class="game-entity-id-<?= $game->getId() ?>">
                <h4 class="game-id">EntityId: <?= $game->getGameId() ?></h4>
                <h5 class="title">StalkerId: <?= $game->getTitle() ?></h5>
                <h6 class="description">SomeId: <?= $game->getDescription() ?></h6>
                <h6 class="price">CarId: <?= $game->getPrice() ?></h6>
                <p class="link">
                    <a class="go-back" href="<?= $block->getUrl('game_route') ?>">Go Back</a>
                </p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>