<?php
/**
 * @var Roma\Game\Block\GameLicense $block
 */
/** @var \Roma\Game\ViewModel\GameLicense $checkGameLicense */
$checkGameLicense = $block->getData('check_license_game');

$id = $block->getGameId();

$answer = $checkGameLicense->checkLicenseGame($id);
?>

<h1>Check license your game!</h1>

<?php if($id!=NULL):?>
<h2>ID = <?= $id ?></h2>
<h1><?= $answer ?></h1>
<?php endif; ?>

<form action="gamelicense" method="post">
    <input required="true" name="gamelicense" type="text" data-validate="number">
    <input type="submit" value="Check!">
</form>
<h2>You may go back</h2>
<a class="read-more" href="<?= $block->getUrl('game_route') ?>">Back</a>